#!/usr/bin/env bash
# This script takes a list of domains as arguments and will setup a single certificate for all of them.
#sudo apt update && sudo apt upgrade -y
sudo apt-get update
sudo apt-get install certbot
sudo netstat -nlp | grep :80


sudo certbot certonly --standalone -d www.thebenjamin.tech

frontend www-https
   bind *:443 ssl crt /etc/letsencrypt/live/www.thebenjamin.tech/fullchain.pem
   default_backend letsencrypt

sudo service haproxy restart
