#!/usr/bin/env bash
# This script takes a list of domains as arguments and will setup a single certificate for all of them.
#sudo apt update && sudo apt upgrade -y
sudo apt-get install haproxy
sudo apt-get update
sudo apt-get install certbot
sudo certbot certonly --standalone -d www.example.com
frontend haproxy_inbound
   bind *:443 ssl crt /etc/letsencrypt/live/www.example.com/fullchain.pem
   default_backend my_servers

sudo service haproxy restart
