#!/usr/bin/env bash
# display information about subdomains
domain_name=$1
if [ $# -eq 1 ]; then
    SUB_DOMAINS=("www" "lb-01" "web-01" "web-02")
    for subdomain in ${SUB_DOMAINS[@]}; do
        record_type="$(dig "$subdomain.$domain_name" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
        destination_ip="$(dig "$subdomain.$domain_name" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
        echo "The subdomain $subdomain is a $record_type record and points to $destination_ip"
    done
else
    subdomain="$2"
    record_type="$(dig "$subdomain.$domain_name" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
    destination_ip="$(dig "$subdomain.$domain_name" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
    echo "The subdomain $subdomain is a $record_type record and points to $destination_ip"
fi
