#!/bin/bash
# This script takes a list of domains as arguments
# and will setup a single certificate for all of them.
sudo apt-get install -y certbot haproxy

cert_name="generic_cert"
haproxy_cert_dir="/etc/haproxy/ssl-certs"
email="b.ishimwe1@alustudent.com"

domains=""
for domain in "$@"
do
  domains+="-d $domain "
done

certbot certonly --standalone --agree-tos --non-interactive \
-m $email --preferred-challenges http \
--http-01-port 9785 --cert-name $cert_name \
--renew-with-new-domains --keep-until-expiring $domains

mkdir -p $haproxy_cert_dir

# Combine the certificate chain

cd /etc/letsencrypt/live/$cert_name
cat fullchain.pem privkey.pem > "$haproxy_cert_dir/cert.pem"

echo "Reloading haproxy"
sudo systemctl reload haproxy

frontend www-https
  bind *:443 ssl crt /etc/haproxy/ssl-certs/cert.pem
  reqadd X-Forwarded-Proto:\ https



  acl letsencrypt-req path_beg /.well-known/acme-challenge/
  use_backend letsencrypt if letsencrypt-req


  backend letsencrypt
   server letsencrypt 127.0.0.1:9785
