#!/bin/bash
# This script takes a list of domains as arguments
# and will setup a single certificate for all of them.
sudo apt-get install -y certbot haproxy

cert_name="generic_cert"
haproxy_cert_dir="/etc/haproxy/ssl-certs"
email="b.ishimwe1@alustudent.com"

domains=""
for domain in "www.thebenjamin.tech"
do
  domains+="-d $domain "
done

certbot certonly --standalone --agree-tos --non-interactive \
-m $email --preferred-challenges http \
--http-01-port 9785 --cert-name $cert_name \
--renew-with-new-domains --keep-until-expiring $domains

mkdir -p $haproxy_cert_dir


cd /etc/letsencrypt/live/$cert_name
cat fullchain.pem privkey.pem > "$haproxy_cert_dir/cert.pem"

echo "Reloading haproxy"
sudo systemctl reload haproxy

